// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdhiiynmlokocelkqsiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkaGlpeW5tbG9rb2NlbGtxc2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjkwMjgsImV4cCI6MjA2MzQwNTAyOH0.6joVgEi8tq2q45G0xQZjv5OLyjCFMwQpUrwf76Y8eig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});